export const productData = [
    {
        id: 1,
        title: "Long Sleeve Jacket",
        isNew: true,
        oldPrice: 200,
        price: 150,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa quas dolorum magni quos id beatae magnam tempore, porro ex totam rerum quis voluptatum, minus et natus atque deserunt vitae nostrum?",
        category: "women",
        image: "https://img.freepik.com/free-photo/medium-shot-woman-wearing-blank-shirt_23-2149345049.jpg?w=360&t=st=1695814995~exp=1695815595~hmac=929bdb6508ab02aa3341bc56cf449d690ce1490ba9ca2c63b5388e5bf0452a4c",
        rating: 4,
        quantity: 1,
    },

    {
        id: 2,
        title: "Compact Fashion t-shirt",
        isNew: true,
        oldPrice: 70,
        price: 55.99,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa quas dolorum magni quos id beatae magnam tempore, porro ex totam rerum quis voluptatum, minus et natus atque deserunt vitae nostrum?",
        category: "women",
        image: "https://img.freepik.com/free-photo/happy-smiling-woman-with-blond-hair-winking-looking-enthusiastic-camera-standing-brown-tshirt-jeans-against-white-background_176420-48162.jpg?w=740&t=st=1695815546~exp=1695816146~hmac=ca0423735edabf01c3cc9de0cb0de438b5ef534161b04e11f665810a61dae16d",
        rating: 3,
        quantity: 3,
    },

    {
        id: 3,
        title: "Denim Jeans",
        isNew: true,
        oldPrice: 70,
        price: 55.99,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa quas dolorum magni quos id beatae magnam tempore, porro ex totam rerum quis voluptatum, minus et natus atque deserunt vitae nostrum?",
        category: "Unisex",
        image: "https://img.freepik.com/free-photo/woman-studio-front-view_23-2148846658.jpg?size=626&ext=jpg&ga=GA1.2.1840156.1691059188&semt=ais",
        rating: 4,
        quantity: 7,
    },

    {
        id: 4,
        title: "Jacket",
        isNew: true,
        oldPrice: 170,
        price: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa quas dolorum magni quos id beatae magnam tempore, porro ex totam rerum quis voluptatum, minus et natus atque deserunt vitae nostrum?",
        category: "Men",
        image: "https://img.freepik.com/free-photo/autumn-person-with-beautiful-hat_23-2149137833.jpg?size=626&ext=jpg&ga=GA1.1.1840156.1691059188&semt=ais",
        rating: 4,
        quantity: 17,
    },
];

export const trendingProducts = [
    {
        id: 1,
        title: "Jacket",
        isNew: true,
        oldPrice: 170,
        price: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa quas dolorum magni quos id beatae magnam tempore, porro ex totam rerum quis voluptatum, minus et natus atque deserunt vitae nostrum?",
        category: "Men",
        image: "https://img.freepik.com/premium-photo/trendy-young-man-casual-clothing-looking-camera-adjusting-eyewear-while-sitting-against-brown-wall_425904-3568.jpg?size=626&ext=jpg&ga=GA1.1.1840156.1691059188&semt=ais",
        rating: 4,
        quantity: 17,
    },

    {
        id: 2,
        title: "Casual",
        isNew: true,
        oldPrice: 120,
        price: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa quas dolorum magni quos id beatae magnam tempore, porro ex totam rerum quis voluptatum, minus et natus atque deserunt vitae nostrum?",
        category: "Women",
        image: "https://img.freepik.com/free-photo/beautiful-woman-autumn-setting_23-2149056529.jpg?size=626&ext=jpg&ga=GA1.1.1840156.1691059188&semt=ais",
        rating: 4,
        quantity: 5,
    },

    {
        id: 3,
        title: "Jacket",
        isNew: true,
        oldPrice: 170,
        price: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa quas dolorum magni quos id beatae magnam tempore, porro ex totam rerum quis voluptatum, minus et natus atque deserunt vitae nostrum?",
        category: "Men",
        image: "https://img.freepik.com/premium-photo/trendy-young-man-casual-clothing-looking-camera-adjusting-eyewear-while-sitting-against-brown-wall_425904-3568.jpg?size=626&ext=jpg&ga=GA1.1.1840156.1691059188&semt=ais",
        rating: 4,
        quantity: 17,
    },

    {
        id: 4,
        title: "Jacket",
        isNew: true,
        oldPrice: 170,
        price: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa quas dolorum magni quos id beatae magnam tempore, porro ex totam rerum quis voluptatum, minus et natus atque deserunt vitae nostrum?",
        category: "Men",
        image: "https://img.freepik.com/premium-photo/trendy-young-man-casual-clothing-looking-camera-adjusting-eyewear-while-sitting-against-brown-wall_425904-3568.jpg?size=626&ext=jpg&ga=GA1.1.1840156.1691059188&semt=ais",
        rating: 4,
        quantity: 17,
    },

    {
        id: 5,
        title: "Coperate",
        isNew: true,
        oldPrice: 170,
        price: 100,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa quas dolorum magni quos id beatae magnam tempore, porro ex totam rerum quis voluptatum, minus et natus atque deserunt vitae nostrum?",
        category: "Men",
        image: "https://img.freepik.com/premium-photo/close-up-luxurious-style-gentlemen-suit-row-hanging-closet_56854-2326.jpg?size=626&ext=jpg&ga=GA1.2.1840156.1691059188&semt=ais",
        rating: 4,
        quantity: 17,
    },
];